import { describe, expect, it, vi } from "vitest";
import { formatDatabaseSchema, readDatabaseSchema, run } from "../scripts/generate-database-schema.mjs";

const schema = {
  tables: [{ table_name: "pubs" }, { table_name: "tags" }],
  columns: [
    {
      table_name: "pubs",
      column_name: "id",
      data_type: "uuid",
      is_nullable: "NO",
      column_default: "gen_random_uuid()",
    },
    {
      table_name: "pubs",
      column_name: "name",
      data_type: "character varying",
      character_maximum_length: 120,
      is_nullable: "YES",
      column_default: null,
    },
    { table_name: "tags", column_name: "id", data_type: "uuid", is_nullable: "NO", column_default: null },
  ],
  constraints: [
    { table_name: "pubs", constraint_name: "pubs_pkey", constraint_type: "p", definition: "PRIMARY KEY (id)" },
    {
      table_name: "tags",
      constraint_name: "tags_pubs_fkey",
      constraint_type: "f",
      definition: "FOREIGN KEY (pub_id) REFERENCES pubs(id)",
    },
  ],
  indexes: [
    {
      table_name: "pubs",
      index_name: "pubs_pkey",
      definition: "CREATE UNIQUE INDEX pubs_pkey ON public.pubs USING btree (id)",
    },
  ],
};

describe("database schema generator", () => {
  it("renders tables, columns, constraints, foreign keys, and indexes in stable order", () => {
    const first = formatDatabaseSchema(schema);
    const second = formatDatabaseSchema({ ...schema, tables: [...schema.tables].reverse() });

    expect(first).toBe(second);
    expect(first).toContain("## pubs");
    expect(first).toContain("`varchar(120)`");
    expect(first).toContain("PRIMARY KEY");
    expect(first).toContain("FOREIGN KEY");
    expect(first).toContain("CREATE UNIQUE INDEX");
    expect(first).toContain("Do not edit this file manually");
  });

  it("issues only catalog reads and does not pass the connection string to queries", async () => {
    const sql = vi.fn(async () => []);
    await expect(readDatabaseSchema("database-url-for-test", sql)).resolves.toEqual({
      tables: [],
      columns: [],
      constraints: [],
      indexes: [],
    });

    expect(sql).toHaveBeenCalledTimes(4);
    for (const [query] of sql.mock.calls) {
      expect(query).toMatch(/^\s*SELECT\b/i);
      expect(query).not.toContain("database-url-for-test");
    }
  });

  it("requires DATABASE_URL and detects stale generated output without exposing its value", async () => {
    await expect(readDatabaseSchema("", vi.fn())).rejects.toThrow("DATABASE_URL is required.");
    await expect(
      run("database-url-for-test", ["--check"], {
        readSchema: vi.fn(async () => schema),
        readOutput: vi.fn(async () => "stale"),
      }),
    ).rejects.toThrow("docs/generated/database-schema.md is out of date");
  });
});
